import pytest
import json

from spotifind.client import get_audio_features, get_top_artists, get_top_tracks

client_id = '98e1af2c2aad45ecad9997543623cbbf'
client_secret = 'bf63ae87996f4f1aad31335abb361d4e'
redirect_uri = 'https://localhost:8888/callback/'
time_range = 'long_term'

# before running tests fill these categories:
token = 'BQDJUlIoQy-oaQ1Q5fI_j9kjB2_H83Tm4Dc_ix0Gf7DWwSX1-Pop75GV6RmPDtELxLavr1blSUd5j0a8ifjAprXofXMzpX1xp2TLI2eh1pEXTg1XLwE5e99IcquccSzuaEUDIkIamLnQbYy_opGSyz9mEhnqlK94re9At96G_w0'
# get token by uncommenting the part where you could get a token, print it out, and then copy here
username = 'AnthonyTech88'


# also redo all the values in the tests


class TestClientValues:
    # def test_get_token(self):
    #     assert get_token(username, "user-top-read user-read-private").exists()

    @pytest.mark.skip(reason="must fill in our own values")
    def test_get_audio_features(self):
        value = [{'acousticness': 0.0417,
                  'analysis_url': 'https://api.spotify.com/v1/audio-analysis/3FoiMgXMrO3D5FeJuotKyZ',
                  'danceability': 0.596,
                  'duration_ms': 209519, 'energy': 0.893, 'id': '3FoiMgXMrO3D5FeJuotKyZ', 'instrumentalness': 0,
                  'key': 1,
                  'liveness': 0.315, 'loudness': -3.43, 'mode': 0, 'speechiness': 0.16, 'tempo': 79.889,
                  'time_signature': 4,
                  'track_href': 'https://api.spotify.com/v1/tracks/3FoiMgXMrO3D5FeJuotKyZ', 'type': 'audio_features',
                  'uri': 'spotify:track:3FoiMgXMrO3D5FeJuotKyZ', 'valence': 0.526}]
        assert get_audio_features(token, '3FoiMgXMrO3D5FeJuotKyZ') == value

    @pytest.mark.skip(reason="must fill in our own values")
    def test_get_top_artists(self):
        value = {'href': 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=0&time_range=long_term',
                 'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6nfDaffa50mKtEOwR8g4df'},
                            'followers': {'href': None, 'total': 2851367},
                            'genres': ['k-pop', 'k-pop boy group'],
                            'href': 'https://api.spotify.com/v1/artists/6nfDaffa50mKtEOwR8g4df',
                            'id': '6nfDaffa50mKtEOwR8g4df',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/b0161d58354d18438747fc17186f78c9277759b4',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/ede0a8e6ccce2fcb7a09676f24a3ec45c2c2f8cb',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/92868c56a6affccdedd2ce51f812853a5b32b603',
                                        'width': 160}],
                            'name': 'GOT7',
                            'popularity': 70,
                            'type': 'artist',
                            'uri': 'spotify:artist:6nfDaffa50mKtEOwR8g4df'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'},
                            'followers': {'href': None, 'total': 52370705},
                            'genres': ['pop', 'uk pop'],
                            'href': 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
                            'id': '6eUKZXaKkcviH0Ku9w2n3V',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/f55cab0739390cf3b2c2f773b9c779b2f0ae8a99',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/31e1cfee4ec3849bf3036a037cbbf57239f5c7a2',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/f2e3eb4c81da6cd2f32036ab0946c6bbfe4a86b7',
                                        'width': 160}],
                            'name': 'Ed Sheeran',
                            'popularity': 96,
                            'type': 'artist',
                            'uri': 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/3Nrfpe0tUJi4K4DXYWgMUX'},
                            'followers': {'href': None, 'total': 13889633},
                            'genres': ['k-pop', 'k-pop boy group'],
                            'href': 'https://api.spotify.com/v1/artists/3Nrfpe0tUJi4K4DXYWgMUX',
                            'id': '3Nrfpe0tUJi4K4DXYWgMUX',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/0c9057cb30520f9f883a220051260fc66a2f3ffa',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/34ee854082d0ea4d571e2ecf7f4aecea61270ad0',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/156147697b696d4a6180e037dc1e2a33117d8d4a',
                                        'width': 160}],
                            'name': 'BTS',
                            'popularity': 90,
                            'type': 'artist',
                            'uri': 'spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'},
                            'followers': {'href': None, 'total': 8754779},
                            'genres': ['pop'],
                            'href': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
                            'id': '6LuN9FCkKOj5PcnpouEgny',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/e52c824585bfeef4d674b509437120805300f557',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/c2a7583b4a35c6b0f0345ec3bd451957cfd36ad4',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/eeb1087bfc99dab83872144d023aadd69fbc5dac',
                                        'width': 160}],
                            'name': 'Khalid',
                            'popularity': 94,
                            'type': 'artist',
                            'uri': 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'},
                            'followers': {'href': None, 'total': 30093188},
                            'genres': ['detroit hip hop', 'g funk', 'hip hop', 'rap'],
                            'href': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
                            'id': '7dGJo4pcD2V6oG8kP0tJRR',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/60c4daa4721f666c6afaee82a39bd413979a0474',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/ae8dd3b01ada324eeb8c0b341e8f7ebda406095e',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/ed213a32e1327f3f2d7b2539eb1db57f55b68dbb',
                                        'width': 160}],
                            'name': 'Eminem',
                            'popularity': 92,
                            'type': 'artist',
                            'uri': 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'},
                            'followers': {'href': None, 'total': 41261039},
                            'genres': ['canadian hip hop',
                                       'canadian pop',
                                       'hip hop',
                                       'pop rap',
                                       'rap',
                                       'toronto rap'],
                            'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',
                            'id': '3TVXtAsR1Inumwj472S9r4',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/012ecd119617ac24ab56620ace4b81735b172686',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/55e3fb26d67b4d71321440b3a440eecd9d8f20f7',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/ad10179d5f27ba77c7d6c95abd6e26f6a227e0d5',
                                        'width': 160}],
                            'name': 'Drake',
                            'popularity': 96,
                            'type': 'artist',
                            'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/246dkjvS1zLTtiykXe5h60'},
                            'followers': {'href': None, 'total': 18349139},
                            'genres': ['dfw rap', 'melodic rap', 'pop', 'rap'],
                            'href': 'https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60',
                            'id': '246dkjvS1zLTtiykXe5h60',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/93fec27f9aac86526b9010e882037afbda4e3d5f',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/9040899d5660920fdf7efeb7aa2cc4e6d86f86f6',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/d15a5ffb3d22adabd09a749e09e846f527ab5a94',
                                        'width': 160}],
                            'name': 'Post Malone',
                            'popularity': 100,
                            'type': 'artist',
                            'uri': 'spotify:artist:246dkjvS1zLTtiykXe5h60'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg'},
                            'followers': {'href': None, 'total': 13294190},
                            'genres': ['conscious hip hop',
                                       'hip hop',
                                       'pop rap',
                                       'rap',
                                       'west coast rap'],
                            'href': 'https://api.spotify.com/v1/artists/2YZyLoL8N0Wb9xBt1NhZWg',
                            'id': '2YZyLoL8N0Wb9xBt1NhZWg',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/3a836196bfb341f736c7fe2704fb75de53f8dfbb',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/5259c0496329b3f608a1ae0edb799cd2f8451acc',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/b772a78d4cb192268d6f601a78f21044c17d6dda',
                                        'width': 160}],
                            'name': 'Kendrick Lamar',
                            'popularity': 88,
                            'type': 'artist',
                            'uri': 'spotify:artist:2YZyLoL8N0Wb9xBt1NhZWg'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI'},
                            'followers': {'href': None, 'total': 10065479},
                            'genres': ['pop', 'uk pop'],
                            'href': 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI',
                            'id': '2wY79sveU1sp5g7SokKOiI',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/43c481adb3f39709882a7058c2c4c7538d79aa17',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/6c484dceeecd500e0eb30c35e396d0b80093eff8',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/4e7454ba7759e5de5462f531bc165d8087b45388',
                                        'width': 160}],
                            'name': 'Sam Smith',
                            'popularity': 90,
                            'type': 'artist',
                            'uri': 'spotify:artist:2wY79sveU1sp5g7SokKOiI'},
                           {'external_urls': {'spotify': 'https://open.spotify.com/artist/2qxJFvFYMEDqd7ui6kSAcq'},
                            'followers': {'href': None, 'total': 4769684},
                            'genres': ['complextro',
                                       'dance pop',
                                       'edm',
                                       'electro house',
                                       'german techno',
                                       'pop',
                                       'post-teen pop',
                                       'tropical house'],
                            'href': 'https://api.spotify.com/v1/artists/2qxJFvFYMEDqd7ui6kSAcq',
                            'id': '2qxJFvFYMEDqd7ui6kSAcq',
                            'images': [{'height': 640,
                                        'url': 'https://i.scdn.co/image/a9c923d081963c77dec430fb842b493724187dcc',
                                        'width': 640},
                                       {'height': 320,
                                        'url': 'https://i.scdn.co/image/4172664dfd6ed2291c5a87aaf90595cf960914c5',
                                        'width': 320},
                                       {'height': 160,
                                        'url': 'https://i.scdn.co/image/bb7b2beeb6af13a0e3f9ad3a9effd5aaaf9dedbd',
                                        'width': 160}],
                            'name': 'Zedd',
                            'popularity': 83,
                            'type': 'artist',
                            'uri': 'spotify:artist:2qxJFvFYMEDqd7ui6kSAcq'}],
                 'limit': 10,
                 'next': 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=10&time_range=long_term',
                 'offset': 0,
                 'previous': None,
                 'total': 50}
        assert get_top_artists(token, 10, time_range) == value

    @pytest.mark.skip(reason="must fill in our own values")
    def test_get_top_tracks(self):
        value = {'href': 'https://api.spotify.com/v1/me/top/tracks?limit=2&offset=0&time_range=long_term',
                 'items': [{'album': {'album_type': 'ALBUM',
                                      'artists': [{'external_urls': {
                                          'spotify': 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'},
                                          'href': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
                                          'id': '6LuN9FCkKOj5PcnpouEgny',
                                          'name': 'Khalid',
                                          'type': 'artist',
                                          'uri': 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'}],
                                      'available_markets': ['AD',
                                                            'AE',
                                                            'AR',
                                                            'AT',
                                                            'AU',
                                                            'BE',
                                                            'BG',
                                                            'BH',
                                                            'BO',
                                                            'BR',
                                                            'CA',
                                                            'CH',
                                                            'CL',
                                                            'CO',
                                                            'CR',
                                                            'CY',
                                                            'CZ',
                                                            'DE',
                                                            'DK',
                                                            'DO',
                                                            'DZ',
                                                            'EC',
                                                            'EE',
                                                            'EG',
                                                            'ES',
                                                            'FI',
                                                            'FR',
                                                            'GB',
                                                            'GR',
                                                            'GT',
                                                            'HK',
                                                            'HN',
                                                            'HU',
                                                            'ID',
                                                            'IE',
                                                            'IL',
                                                            'IN',
                                                            'IS',
                                                            'IT',
                                                            'JO',
                                                            'JP',
                                                            'KW',
                                                            'LB',
                                                            'LI',
                                                            'LT',
                                                            'LU',
                                                            'LV',
                                                            'MA',
                                                            'MC',
                                                            'MT',
                                                            'MX',
                                                            'MY',
                                                            'NI',
                                                            'NL',
                                                            'NO',
                                                            'NZ',
                                                            'OM',
                                                            'PA',
                                                            'PE',
                                                            'PH',
                                                            'PL',
                                                            'PS',
                                                            'PT',
                                                            'PY',
                                                            'QA',
                                                            'RO',
                                                            'SA',
                                                            'SE',
                                                            'SG',
                                                            'SK',
                                                            'SV',
                                                            'TH',
                                                            'TN',
                                                            'TR',
                                                            'TW',
                                                            'US',
                                                            'UY',
                                                            'VN',
                                                            'ZA'],
                                      'external_urls': {
                                          'spotify': 'https://open.spotify.com/album/6kf46HbnYCZzP6rjvQHYzg'},
                                      'href': 'https://api.spotify.com/v1/albums/6kf46HbnYCZzP6rjvQHYzg',
                                      'id': '6kf46HbnYCZzP6rjvQHYzg',
                                      'images': [{'height': 640,
                                                  'url': 'https://i.scdn.co/image/ab67616d0000b273988ede5e1276e758b5f9e577',
                                                  'width': 640},
                                                 {'height': 300,
                                                  'url': 'https://i.scdn.co/image/ab67616d00001e02988ede5e1276e758b5f9e577',
                                                  'width': 300},
                                                 {'height': 64,
                                                  'url': 'https://i.scdn.co/image/ab67616d00004851988ede5e1276e758b5f9e577',
                                                  'width': 64}],
                                      'name': 'American Teen',
                                      'release_date': '2017-04-27',
                                      'release_date_precision': 'day',
                                      'total_tracks': 15,
                                      'type': 'album',
                                      'uri': 'spotify:album:6kf46HbnYCZzP6rjvQHYzg'},
                            'artists': [
                                {'external_urls': {'spotify': 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'},
                                 'href': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
                                 'id': '6LuN9FCkKOj5PcnpouEgny',
                                 'name': 'Khalid',
                                 'type': 'artist',
                                 'uri': 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'}],
                            'available_markets': ['AD',
                                                  'AE',
                                                  'AR',
                                                  'AT',
                                                  'AU',
                                                  'BE',
                                                  'BG',
                                                  'BH',
                                                  'BO',
                                                  'BR',
                                                  'CA',
                                                  'CH',
                                                  'CL',
                                                  'CO',
                                                  'CR',
                                                  'CY',
                                                  'CZ',
                                                  'DE',
                                                  'DK',
                                                  'DO',
                                                  'DZ',
                                                  'EC',
                                                  'EE',
                                                  'EG',
                                                  'ES',
                                                  'FI',
                                                  'FR',
                                                  'GB',
                                                  'GR',
                                                  'GT',
                                                  'HK',
                                                  'HN',
                                                  'HU',
                                                  'ID',
                                                  'IE',
                                                  'IL',
                                                  'IN',
                                                  'IS',
                                                  'IT',
                                                  'JO',
                                                  'JP',
                                                  'KW',
                                                  'LB',
                                                  'LI',
                                                  'LT',
                                                  'LU',
                                                  'LV',
                                                  'MA',
                                                  'MC',
                                                  'MT',
                                                  'MX',
                                                  'MY',
                                                  'NI',
                                                  'NL',
                                                  'NO',
                                                  'NZ',
                                                  'OM',
                                                  'PA',
                                                  'PE',
                                                  'PH',
                                                  'PL',
                                                  'PS',
                                                  'PT',
                                                  'PY',
                                                  'QA',
                                                  'RO',
                                                  'SA',
                                                  'SE',
                                                  'SG',
                                                  'SK',
                                                  'SV',
                                                  'TH',
                                                  'TN',
                                                  'TR',
                                                  'TW',
                                                  'US',
                                                  'UY',
                                                  'VN',
                                                  'ZA'],
                            'disc_number': 1,
                            'duration_ms': 219080,
                            'explicit': False,
                            'external_ids': {'isrc': 'TCACO1662934'},
                            'external_urls': {'spotify': 'https://open.spotify.com/track/152lZdxL1OR0ZMW6KquMif'},
                            'href': 'https://api.spotify.com/v1/tracks/152lZdxL1OR0ZMW6KquMif',
                            'id': '152lZdxL1OR0ZMW6KquMif',
                            'is_local': False,
                            'name': 'Location',
                            'popularity': 83,
                            'preview_url': 'https://p.scdn.co/mp3-preview/d50dfb78af7cb29f6363ba1a0d2cbdd707ee137c?cid=98e1af2c2aad45ecad9997543623cbbf',
                            'track_number': 3,
                            'type': 'track',
                            'uri': 'spotify:track:152lZdxL1OR0ZMW6KquMif'},
                           {'album': {'album_type': 'ALBUM',
                                      'artists': [{'external_urls': {
                                          'spotify': 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'},
                                          'href': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
                                          'id': '6LuN9FCkKOj5PcnpouEgny',
                                          'name': 'Khalid',
                                          'type': 'artist',
                                          'uri': 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'}],
                                      'available_markets': ['AD',
                                                            'AE',
                                                            'AR',
                                                            'AT',
                                                            'AU',
                                                            'BE',
                                                            'BG',
                                                            'BH',
                                                            'BO',
                                                            'BR',
                                                            'CA',
                                                            'CH',
                                                            'CL',
                                                            'CO',
                                                            'CR',
                                                            'CY',
                                                            'CZ',
                                                            'DE',
                                                            'DK',
                                                            'DO',
                                                            'DZ',
                                                            'EC',
                                                            'EE',
                                                            'EG',
                                                            'ES',
                                                            'FI',
                                                            'FR',
                                                            'GB',
                                                            'GR',
                                                            'GT',
                                                            'HK',
                                                            'HN',
                                                            'HU',
                                                            'ID',
                                                            'IE',
                                                            'IL',
                                                            'IN',
                                                            'IS',
                                                            'IT',
                                                            'JO',
                                                            'JP',
                                                            'KW',
                                                            'LB',
                                                            'LI',
                                                            'LT',
                                                            'LU',
                                                            'LV',
                                                            'MA',
                                                            'MC',
                                                            'MT',
                                                            'MX',
                                                            'MY',
                                                            'NI',
                                                            'NL',
                                                            'NO',
                                                            'NZ',
                                                            'OM',
                                                            'PA',
                                                            'PE',
                                                            'PH',
                                                            'PL',
                                                            'PS',
                                                            'PT',
                                                            'PY',
                                                            'QA',
                                                            'RO',
                                                            'SA',
                                                            'SE',
                                                            'SG',
                                                            'SK',
                                                            'SV',
                                                            'TH',
                                                            'TN',
                                                            'TR',
                                                            'TW',
                                                            'US',
                                                            'UY',
                                                            'VN',
                                                            'ZA'],
                                      'external_urls': {
                                          'spotify': 'https://open.spotify.com/album/6kf46HbnYCZzP6rjvQHYzg'},
                                      'href': 'https://api.spotify.com/v1/albums/6kf46HbnYCZzP6rjvQHYzg',
                                      'id': '6kf46HbnYCZzP6rjvQHYzg',
                                      'images': [{'height': 640,
                                                  'url': 'https://i.scdn.co/image/ab67616d0000b273988ede5e1276e758b5f9e577',
                                                  'width': 640},
                                                 {'height': 300,
                                                  'url': 'https://i.scdn.co/image/ab67616d00001e02988ede5e1276e758b5f9e577',
                                                  'width': 300},
                                                 {'height': 64,
                                                  'url': 'https://i.scdn.co/image/ab67616d00004851988ede5e1276e758b5f9e577',
                                                  'width': 64}],
                                      'name': 'American Teen',
                                      'release_date': '2017-04-27',
                                      'release_date_precision': 'day',
                                      'total_tracks': 15,
                                      'type': 'album',
                                      'uri': 'spotify:album:6kf46HbnYCZzP6rjvQHYzg'},
                            'artists': [
                                {'external_urls': {'spotify': 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'},
                                 'href': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
                                 'id': '6LuN9FCkKOj5PcnpouEgny',
                                 'name': 'Khalid',
                                 'type': 'artist',
                                 'uri': 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'}],
                            'available_markets': ['AD',
                                                  'AE',
                                                  'AR',
                                                  'AT',
                                                  'AU',
                                                  'BE',
                                                  'BG',
                                                  'BH',
                                                  'BO',
                                                  'BR',
                                                  'CA',
                                                  'CH',
                                                  'CL',
                                                  'CO',
                                                  'CR',
                                                  'CY',
                                                  'CZ',
                                                  'DE',
                                                  'DK',
                                                  'DO',
                                                  'DZ',
                                                  'EC',
                                                  'EE',
                                                  'EG',
                                                  'ES',
                                                  'FI',
                                                  'FR',
                                                  'GB',
                                                  'GR',
                                                  'GT',
                                                  'HK',
                                                  'HN',
                                                  'HU',
                                                  'ID',
                                                  'IE',
                                                  'IL',
                                                  'IN',
                                                  'IS',
                                                  'IT',
                                                  'JO',
                                                  'JP',
                                                  'KW',
                                                  'LB',
                                                  'LI',
                                                  'LT',
                                                  'LU',
                                                  'LV',
                                                  'MA',
                                                  'MC',
                                                  'MT',
                                                  'MX',
                                                  'MY',
                                                  'NI',
                                                  'NL',
                                                  'NO',
                                                  'NZ',
                                                  'OM',
                                                  'PA',
                                                  'PE',
                                                  'PH',
                                                  'PL',
                                                  'PS',
                                                  'PT',
                                                  'PY',
                                                  'QA',
                                                  'RO',
                                                  'SA',
                                                  'SE',
                                                  'SG',
                                                  'SK',
                                                  'SV',
                                                  'TH',
                                                  'TN',
                                                  'TR',
                                                  'TW',
                                                  'US',
                                                  'UY',
                                                  'VN',
                                                  'ZA'],
                            'disc_number': 1,
                            'duration_ms': 250746,
                            'explicit': False,
                            'external_ids': {'isrc': 'USRC11602480'},
                            'external_urls': {'spotify': 'https://open.spotify.com/track/312WNtMs3F28cUukaPY9bo'},
                            'href': 'https://api.spotify.com/v1/tracks/312WNtMs3F28cUukaPY9bo',
                            'id': '312WNtMs3F28cUukaPY9bo',
                            'is_local': False,
                            'name': 'American Teen',
                            'popularity': 74,
                            'preview_url': 'https://p.scdn.co/mp3-preview/3b4aa1b644a30474a3383594acf8b6ba6eba7fda?cid=98e1af2c2aad45ecad9997543623cbbf',
                            'track_number': 1,
                            'type': 'track',
                            'uri': 'spotify:track:312WNtMs3F28cUukaPY9bo'}],
                 'limit': 2,
                 'next': 'https://api.spotify.com/v1/me/top/tracks?limit=2&offset=2&time_range=long_term',
                 'offset': 0,
                 'previous': None,
                 'total': 50}
        assert get_top_tracks(token, 2, time_range) == value


class TestClientNull:
    def test_not_null_get_audio_features(self):
        assert get_audio_features(token, '3FoiMgXMrO3D5FeJuotKyZ') is not None

    def test_not_null_get_top_artists(self):
        assert get_top_artists(token, 50, 'short_term') is not None
        assert get_top_artists(token, 50, 'medium_term') is not None
        assert get_top_artists(token, 50, 'long_term') is not None

    def test_not_null_get_top_tracks(self):
        assert get_top_tracks(token, 50, 'short_term') is not None
        assert get_top_tracks(token, 50, 'medium_term') is not None
        assert get_top_tracks(token, 50, 'long_term') is not None
